runtime: custom 
env: flex
manual_scaling:
  instances: 1
resources: 
  memory_gb: 1
env_variables: 
  NODE_ENV: production
  MONGODB_URI: mongosh "mongodb+srv://snodgrass32:OU67hNwHuyfbRet1@cluster0.ggsb9ib.mongodb.net/myFirstDatabase" --apiVersion 1 --username <username>
